Bankmanagement/Bankmanagement/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('customer.urls'))
]

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Bankmanagement/customer/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.Index.as_view()),
    path('addcust', views.Addcust.as_view()),  
    path('display',views.Display.as_view()),  
    path('edit/<int:id>', views.Update.as_view()),  
    path('update/<int:id>', views.Update.as_view()),  
    path('delete/<int:id>', views.Delete.as_view()),  
]

Bankmanagement/customer/models.py
from django.db import models
from django.forms.widgets import Widget



class Customer(models.Model):
    card_company = (
        ('Visa', 'Visa'),
        ('MasterCard', 'MasterCard'),
        ('Rupay', 'Rupay'),
        ('NA', 'NA')
    )

    id = models.AutoField(db_column='ID',primary_key=True) 
    name = models.CharField(db_column='Name', max_length=30)  
    cust_image = models.ImageField(db_column='Photo_customer',upload_to='')
    cardcompany = models.CharField(choices=card_company, max_length=10, default="NA")
    typeofCust = models.BooleanField(db_column='cust_type')
    age = models.IntegerField(db_column='Age')
    opening_date = models.DateField(db_column='openingDate') 
    balance_left = models.FloatField(db_column='Balance')
    email = models.EmailField(db_column='Email', max_length=60)
    phno = models.CharField(db_column='Ph_number', max_length=20)
    Address = models.TextField(db_column='Address')
    Type_loans = models.TextField()
    
    class Meta:
        db_table = 'bankingsystem'
        

Bankmanagement/customer/forms.py
from django import forms  
from customer.models import Customer  


class CustomerForm(forms.ModelForm):
    class Meta:

        customer_type = (
            ('Yes', True),
            ('No', False)
        )
        Loans_taken = (
            ('Home', 'Home'), 
            ('Vehicle', 'Vehicle'), 
            ('Gold', 'Gold'), 
            ('None', 'None')
        )

        model = Customer
        fields = ("id","name","email","phno","cardcompany","typeofCust",'age','opening_date', 'balance_left', 'Type_loans', 'Address', 'cust_image')
        widgets = {
        'id':forms.HiddenInput(),
        'name': forms.TextInput(),
        'email': forms.EmailInput(),
        'phno': forms.NumberInput(),
        'typeofCust': forms.RadioSelect(choices=customer_type),
        'age': forms.NumberInput(),
        'opening_date': forms.DateInput(format=('%d/%m/%Y'), attrs={'class':'form-control', 'placeholder':'Select a date', 'type':'date','required':True}),
        'Type_loans': forms.CheckboxSelectMultiple(choices=Loans_taken),
        'Address': forms.Textarea(attrs={'rows': 5, 'cols': 30}),
        'cust_image': forms.FileInput(),
        }

Bankmanagement/customer/views.py
from django.shortcuts import render,redirect
from customer.forms import CustomerForm  
from customer.models import Customer  
from django.views import View

# Addcust your views here.  

class Index(View):
    def get(self, request):
        return redirect('/display')

class Addcust(View):
    def get(self, request):
        form = CustomerForm()  
        return render(request,'addcust.html',{'form':form})  

    def post(self, request):
        form = CustomerForm(request.POST,request.FILES) 
        if form.is_valid():  
            form.save()  
            return redirect('/display')  
            
class Display(View):
    def get(self, request):
        customers = Customer.objects.all()  
        return render(request,"display.html",{'customers':customers}) 


class Update(View):
    def get(self, request,id):
        customer = Customer.objects.get(id=id)  
        return render(request,'update.html', {'customer':customer})  

    def post(self,request,id):
        customer = Customer.objects.get(id=id)  
        for i in request.POST:
            if i == 'name':
                if customer.name != request.POST['name']:
                    customer.name = request.POST['name']
            if i == 'email':
                if customer.email != request.POST['email']:
                    customer.email = request.POST['email']
            if i == 'phno':
                if customer.phno != request.POST['phno']:
                    customer.phno = request.POST['phno']
            if i == 'cardcompany':
                if customer.cardcompany != request.POST['cardcompany']:
                    customer.cardcompany = request.POST['cardcompany']
            if i == 'typeofCust':
                if customer.typeofCust != request.POST['typeofCust'] and request.POST['typeofCust'] != '':
                    customer.typeofCust = request.POST['typeofCust']
            if i == 'age':
                if customer.age != request.POST['age']:
                    customer.age = request.POST['age']
            if i == 'opening_date':
                if customer.opening_date != request.POST['opening_date'] and request.POST['opening_date'] != '':
                    customer.opening_date = request.POST['opening_date']
            if i == 'balance_left':
                if customer.balance_left != request.POST['balance_left']:
                    customer.balance_left = request.POST['balance_left']
            if i == 'Address':
                if customer.Address != request.POST['Address']:
                    customer.Address = request.POST['Address']
            if i == 'cust_image':
                if request.POST['cust_image'] != '':
                    customer.cust_image = request.FILES['cust_image']
        for i in request.FILES:
            if i == 'cust_image':
                if request.FILES['cust_image'] != '':
                    customer.cust_image = request.FILES['cust_image']
        customer.save()
        return redirect("/display")  



class Delete(View):
    def get(self,request,id):
        customer = Customer.objects.get(id=id)  
        customer.delete()  
        return redirect("/display")      

Bankmanagement/templates/addcust.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Addcust</title>  
    {% load static %} 
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>   
    <style>
        *{
            margin-top:.2cm;
            margin-bottom:.2cm;
            margin-left:.2cm;
        }
    </style>
</head>  
<body>  
<form method="POST" class="post-form" action="/addcust" enctype="multipart/form-data">  
        {% csrf_token %}  
        <div>  
          <br>    
              <h3>Customer Details</h3>   

              <label>CUSTOMER ID:</label>  
              <div>  
                {{ form.id }}  
              </div>  
             
             
              <label>CUST. NAME:</label>  
              <div>  
                {{ form.name }}  
              </div>  

              <label>PHOTO ID:</label>      
              <div>  
                  {{ form.cust_image }}
              </div>

              <label>CUST. EMAIL:</label>  
              <div>  
                {{ form.email }}  
              </div>  
 
              <label>PH. NO. :</label>  
              <div>  
                {{ form.phno }}  
              </div>  
 
              <label>CARD TYPE:</label>      
              <div>  
                  {{ form.cardcompany }}  
              </div>
   

              <label>PLATINUM CUSTOMER:</label>      
              <div>  
                  {% for i in form.typeofCust %}
                  {{ i }}  
                  {% endfor %}
                  
              </div>
   
  
              <label>AGE:</label>      
              <div>  
                  {{ form.age }}
              </div>
   
          

              <label>ACC. OPEN DATE:</label>      
              <div>  
                  {{ form.opening_date }}
              </div>
   

              <label>BALANCE LEFT:</label>      
              <div>  
                  {{ form.balance_left }}
              </div>   

              <label>TYPE OF LOANS TAKEN:</label>      
              <div>  
                  {% for i in form.Type_loans %}
                  {{ i }}
                  {% endfor %} 
                  
              </div>
 
  
              <label>ADDRESS:</label>      
              <div>  
                  {{ form.Address }}
                  
              </div>

              <button type="submit">REGISTER</button>  
  
   
          </div> 
</form> 

</body>  
</html>  

Bankmanagement/templates/create.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Create</title>  
    {% load static %} 
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>   
    
</head>  
<body>  
<form method="POST" class="post-form" action="/create" enctype="multipart/form-data">  
        {% csrf_token %}  
        <div class="container">  
          <br>    
              <h3>Customer Details</h3>   

              <label>CUSTOMER ID:</label>  
              <div>  
                {{ form.id }}  
              </div>  
             
             
              <label>CUST. NAME:</label>  
              <div>  
                {{ form.name }}  
              </div>  
              
              <label>CUST. EMAIL:</label>  
              <div>  
                {{ form.email }}  
              </div>  
 
              <label>PH. NO. :</label>  
              <div>  
                {{ form.phno }}  
              </div>  
 
          

              <label>CARD TYPE:</label>      
              <div>  
                  {{ form.cardcompany }}  
              </div>
   

              <label>PLATINUM CUSTOMER:</label>      
              <div>  
                  {% for i in form.typeofCust %}
                  {{ i }}  
                  {% endfor %}
                  
              </div>
   
  
              <label>AGE:</label>      
              <div>  
                  {{ form.age }}
              </div>
   
          

              <label>ACC. OPEN DATE:</label>      
              <div>  
                  {{ form.opening_date }}
              </div>
   

              <label>BALANCE LEFT:</label>      
              <div>  
                  {{ form.balance_left }}
              </div>   

              <label>TYPE OF LOANS TAKEN:</label>      
              <div>  
                  {% for i in form.Type_loans %}
                  {{ i }}
                  {% endfor %} 
                  
              </div>
 
  
              <label>ADDRESS:</label>      
              <div class="col-sm-4">  
                  {{ form.Address }}
                  
              </div>


              <label>PHOTO ID:</label>      
              <div>  
                  {{ form.cust_image }}
              </div>

              <button type="submit">REGISTER</button>  
  
   
          </div> 
</form> 

 
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</body>  
</html>  

Bankmanagement/templates/display.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Customer Records</title>  
     {% load static %}  
     <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
     <style>
        table, th, td {
          border: 1px solid black;
          border-collapse: collapse;
        }
    </style>
    
</head>  
<body>  
    <h1>WELCOME TO BANKING CRUD APPLICATION</h1>
<br><br>
<table>  
    <thead>  
    <tr>  
        <th>CUSTOMER ID</th>  
        <th>PHOTO ID</th>
        <th>CUST. Name</th>  
        <th>CUST. EMAIL</th>  
        <th>PH. NO.</th>  
        <th>CARD TYPE</th>  
        <th>PLATINUM MEMBER?</th>  
        <th>Age</th>
        <th>ACC. OPEN DATE</th>
        <th>BALANCE LEFT</th>
        <th>TYPES OF LOAN TAKEN</th>
        <th>ADDRESS</th>
        <th>EDIT/DEL</th>  
    </tr>  
    </thead>  
    <tbody>  
{% for customer in customers %}  
    <tr>  
        <td>{{ customer.id }}</td> 
        <td><img src="media/{{customer.cust_image}}" width=150 height=150></td>
        <td>{{ customer.name }}</td>  
        <td>{{ customer.email }}</td>  
        <td>{{ customer.phno }}</td>  
        <td>{{ customer.cardcompany }}</td>  
        <td>{{ customer.typeofCust }}</td>  
        <td>{{ customer.age }}</td>  
        <td>{{ customer.opening_date }}</td>  
        <td>{{ customer.balance_left }}</td>  
        <td>{{ customer.Type_loans }}</td>  
        <td>{{ customer.Address }}</td>  
        
        <td>  
            <a href="/edit/{{ customer.id }}">Edit</span></a>  
            <a href="/delete/{{ customer.id }}">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br><br><br>   
<a href="/addcust">Add Customer</a>
</body>  
</html>  

Bankmanagement/templates/read.html
{% load static %}

<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Customer Records</title>  
     {% load static %}  
    
</head>  
<body>  
    <h2>WELCOME TO BANKING CRUD APPLICATION</h2>
<br><br>
<table>  
    <thead>  
    <tr>  
        <th>CUSTOMER ID</th>  
        <th>CUST. Name</th>  
        <th>CUST. EMAIL</th>  
        <th>PH. NO.</th>  
        <th>CARD TYPE</th>  
        <th>PLATINUM MEMBER?</th>  
        <th>Age</th>
        <th>ACC. OPEN DATE</th>
        <th>BALANCE LEFT</th>
        <th>TYPES OF LOAN TAKEN</th>
        <th>ADDRESS</th>
        <th>PHOTO ID</th>
        <th>EDIT/DEL</th>  
    </tr>  
    </thead>  
    <tbody>  
{% for customer in customers %}  
    <tr>  
        <td>{{ customer.id }}</td>  
        <td>{{ customer.name }}</td>  
        <td>{{ customer.email }}</td>  
        <td>{{ customer.phno }}</td>  
        <td>{{ customer.cardcompany }}</td>  
        <td>{{ customer.typeofCust }}</td>  
        <td>{{ customer.age }}</td>  
        <td>{{ customer.opening_date }}</td>  
        <td>{{ customer.balance_left }}</td>  
        <td>{{ customer.Type_loans }}</td>  
        <td>{{ customer.Address }}</td>  
        <td><img src="media/{{customer.cust_image}}" width=75 height=75></td>
        <td>  
            <a href="/edit/{{ customer.id }}">Edit</span></a>  
            <a href="/delete/{{ customer.id }}">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br><br><br>   
<a href="/create">Add Customer</a>
</body>  
</html>  

Bankmanagement/templates/update.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>update</title>  
    {% load static %}
    <style>
      *{
          margin-top:.2cm;
          margin-bottom:.2cm;
          margin-left:.2cm;
      }
  </style>
    
</head>  
<body>  
<form method="POST" class="post-form" action="/update/{{customer.id}}"  enctype="multipart/form-data">  
        {% csrf_token %}  
    <div>  
<br>  
 
    <div>  
    <h3>Update Customer Details</h3>  
    </div>  

  
    <label>CUSTOMER ID:</label>  
    <div>  
        <input type="text" name="id" id="id_id" required maxlength="20" value="{{ customer.id }}" disabled/>  
    </div>  


    <label>CUST. NAME:</label>  
    <div>  
        <input type="text" name="name" id="id_name" required maxlength="100" value="{{ customer.name }}" />  
    </div>  

    <label>PHOTO ID:</label>  
    <div>  
      <input type="file" name="cust_image" accept="image/*" id="id_cust_image" value="{{ customer.cust_image }}">
    </div>  
   
    <label>CUST. EMAIL:</label>  
    <div>  
        <input type="email" name="email" id="id_email" required maxlength="254" value="{{ customer.email }}" />  
    </div>  

     
    <label>PH. NO.:</label>  
    <div>  
        <input type="number" name="phno" id="id_phno" required maxlength="15" value="{{ customer.phno }}" />  
    </div>  

 
    <label>CARD TYPE:</label>  
    <div>  
      <select name="cardcompany" id="id_cardcompany" selected="{{customer.cardcompany}}">
        <option selected value="{{customer.cardcompany}}">
          
        </option>
        <option value="Visa">Visa</option>
      
        <option value="Mastercard">Mastercard</option>
      
        <option value="Rupay">Rupay</option>
      
        <option value="NA" >NA</option>
      
      </select>
    </div>  
 

  
    <label>PLATINUM MEMBER:</label>  
    <div>  
      <label for="id_typeofCust_0"><input type="radio" name="typeofCust" value="True" id="id_typeofCust_0">
        True</label>
      <label for="id_typeofCust_1"><input type="radio" name="typeofCust" value="False" id="id_typeofCust_1">
        False</label>
    </div>  

  
  
    <label>AGE:</label>  
    <div>  
      <input type="number" name="age" required id="id_age" value="{{ customer.age }}">
    </div>  


   
    <label>ACC. OPEN DATE:</label>  
    <div>  
      <input type="date" name="opening_date" class="form-control" id="id_opening_date" value="{{ customer.opening_date }}">
    </div>  


   
    <label>BALANCE LEFT:</label>  
    <div>  
      <input type="number" name="balance_left" step="any" required id="id_balance_left" value="{{ customer.balance_left }}">
    </div>  


 
    <label>TYPES OF LOANS TAKEN:</label>  
    <div>  
      <label  for="id_Type_loans_0"><input type="checkbox" name="Type_loans" value="Home" id="id_Type_loans_0" >Home</label>
      <label for="id_Type_loans_1"><input type="checkbox" name="Type_loans" value="Vehicle" id="id_Type_loans_1">Vehicle</label>
      <label for="id_Type_loans_2"><input type="checkbox" name="Type_loans" value="Gold" id="id_Type_loans_2">Gold</label>
      <label for="id_Type_loans_3"><input type="checkbox" name="Type_loans" value="None" id="id_Type_loans_3">None</label>
    </div>  


  
    <label>ADDRESS:</label>  
    <div>  
      <textarea name="Address" cols="30" rows="5" required id="id_bio">{{ customer.Address }}</textarea>
    </div>  
  
    <div>  
    <button type="submit">UPDATE</button>  
    </div>  
</div>  
 
</form>  
</html>